version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000" # Map host port 8000 to container port 8000
    volumes:
      - ./ml:/app/ml # Mount the ml directory
      # You might want to mount ./backend:/app/backend for development for live reload
      # - ./backend:/app/backend 
    networks:
      - app-network
    # restart: unless-stopped # Optional: for auto-restart

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "8501:8501" # Map host port 8501 to container port 8501
    depends_on:
      - backend # Ensures backend starts before frontend (optional, but good practice)
    networks:
      - app-network
    # restart: unless-stopped # Optional: for auto-restart
    # You might need to pass the backend URL to the frontend
    environment:
      - BACKEND_URL=http://backend:8000

networks:
  app-network:
    driver: bridge 